package com.driveeasy.ui;

import com.driveeasy.model.Car;
import com.driveeasy.model.enums.CarCategory;
import com.driveeasy.service.CarService;
import com.driveeasy.service.CustomerService;
import com.driveeasy.service.ReservationService;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.util.List;
import java.util.Scanner;

/**
 * Optional console UI for manual testing.
 *
 * FIX #5: Originally instantiated services with "new CarService()" etc., bypassing
 * Spring — repositories were never injected, causing NullPointerException on every call.
 * Converted to @Component + CommandLineRunner so Spring injects fully-wired beans.
 *
 * FIX #1-3: Removed Phase-1 constructor calls (Car/Customer/Reservation with raw IDs).
 * FIX #6-10: Updated all service calls to match Phase-2 API signatures.
 *
 * Only active under the "console" profile:
 *   java -jar app.jar --spring.profiles.active=console
 */
@Component
@Profile("console")
public class ConsoleApp implements CommandLineRunner {

    private final CarService carService;
    private final CustomerService customerService;
    private final ReservationService reservationService;
    private final Scanner scanner = new Scanner(System.in);

    public ConsoleApp(CarService carService,
                      CustomerService customerService,
                      ReservationService reservationService) {
        this.carService = carService;
        this.customerService = customerService;
        this.reservationService = reservationService;
    }

    @Override
    public void run(String... args) {
        System.out.println("=== Welcome to DriveEasy Rentals ===");
        while (true) {
            try {
                System.out.println("\n1. Admin  2. Staff  0. Exit");
                System.out.print("Choose option: ");
                int choice = Integer.parseInt(scanner.nextLine().trim());
                switch (choice) {
                    case 1 -> adminMenu();
                    case 2 -> staffMenu();
                    case 0 -> { System.out.println("Goodbye!"); return; }
                    default -> System.out.println("Invalid choice");
                }
            } catch (Exception e) {
                System.out.println("Error: " + e.getMessage());
            }
        }
    }

    private void adminMenu() {
        System.out.println("\n--- Admin ---");
        System.out.println("1. Add Car  2. Update Pricing  3. Mark Maintenance  4. Mark Available");
        System.out.print("Choice: ");
        try {
            switch (Integer.parseInt(scanner.nextLine().trim())) {
                case 1 -> addCar();
                case 2 -> updateCarPrice();
                case 3 -> { System.out.print("Car ID: "); carService.markUnderMaintenance(readLong()); System.out.println("Done"); }
                case 4 -> { System.out.print("Car ID: "); carService.markAvailable(readLong()); System.out.println("Done"); }
                default -> System.out.println("Invalid");
            }
        } catch (RuntimeException e) { System.out.println("Error: " + e.getMessage()); }
    }

    private void addCar() {
        System.out.print("Model: ");          String model      = scanner.nextLine();
        System.out.print("Category (ECONOMY/SEDAN/SUV/LUXURY): ");
        CarCategory cat = CarCategory.valueOf(scanner.nextLine().toUpperCase());
        System.out.print("Base Fare: ");      double base   = readDouble();
        System.out.print("Per Km Rate: ");    double km     = readDouble();
        System.out.print("Per Hour Rate: ");  double hr     = readDouble();
        // FIX: no manual ID — auto-generated by JPA
        carService.addCar(model, cat, base, km, hr);
        System.out.println("Car added successfully");
    }

    private void updateCarPrice() {
        System.out.print("Car ID: ");         long id   = readLong();
        System.out.print("New Base Fare: ");  double b  = readDouble();
        System.out.print("New Per Km Rate: ");double k  = readDouble();
        System.out.print("New Per Hr Rate: ");double h  = readDouble();
        carService.updateCarPricing(id, b, k, h);
        System.out.println("Pricing updated");
    }

    private void staffMenu() {
        System.out.println("\n--- Staff ---");
        System.out.println("1. Register Customer  2. Book Car  3. Cancel  4. Available Cars");
        System.out.print("Choice: ");
        try {
            switch (Integer.parseInt(scanner.nextLine().trim())) {
                case 1 -> registerCustomer();
                case 2 -> bookCar();
                case 3 -> cancelReservation();
                case 4 -> searchAvailableCars();
                default -> System.out.println("Invalid");
            }
        } catch (RuntimeException e) { System.out.println("Error: " + e.getMessage()); }
    }

    private void registerCustomer() {
        System.out.print("Name: ");    String name  = scanner.nextLine();
        System.out.print("Email: ");   String email = scanner.nextLine();
        System.out.print("Phone: ");   String phone = scanner.nextLine();
        System.out.print("License (Enter to skip): ");
        String lic = scanner.nextLine().trim();
        // FIX: no manual ID; service signature is (name, email, phone, licenseNumber)
        customerService.registerCustomer(name, email, phone, lic.isEmpty() ? null : lic);
        System.out.println("Customer registered");
    }

    private void bookCar() {
        System.out.print("Car ID: ");        long carId   = readLong();
        System.out.print("Customer ID: ");   long custId  = readLong();
        System.out.print("Start (YYYY-MM-DD): "); LocalDate start = LocalDate.parse(scanner.nextLine().trim());
        System.out.print("End (YYYY-MM-DD): ");   LocalDate end   = LocalDate.parse(scanner.nextLine().trim());
        System.out.print("Distance (km): "); double km   = readDouble();
        System.out.print("Duration (hrs): ");double hrs  = readDouble();
        // FIX: bookCar(carId, customerId, start, end, km, hrs) — no manual fare
        var r = reservationService.bookCar(carId, custId, start, end, km, hrs);
        System.out.printf("Booked! Reservation #%d — \u20b9%.2f%n", r.getId(), r.getTotalFare());
    }

    private void cancelReservation() {
        System.out.print("Reservation ID: "); long id = readLong();
        System.out.print("Reason (Enter to skip): ");
        String reason = scanner.nextLine().trim();
        // FIX: two-arg cancelReservation(id, reason)
        reservationService.cancelReservation(id, reason.isEmpty() ? null : reason);
        System.out.println("Cancelled");
    }

    private void searchAvailableCars() {
        System.out.print("Start (YYYY-MM-DD): "); LocalDate start = LocalDate.parse(scanner.nextLine().trim());
        System.out.print("End (YYYY-MM-DD): ");   LocalDate end   = LocalDate.parse(scanner.nextLine().trim());
        // FIX: method is findAvailableCars (not searchAvailableCars)
        List<Car> cars = carService.findAvailableCars(start, end);
        if (cars.isEmpty()) { System.out.println("No cars available"); return; }
        cars.forEach(c -> System.out.printf("ID:%d | %s | %s | Base:\u20b9%.0f | Km:\u20b9%.0f | Hr:\u20b9%.0f%n",
                c.getId(), c.getModel(), c.getCategory().getDisplayName(),
                c.getBaseFare(), c.getPerKmRate(), c.getPerHourRate()));
    }

    private long   readLong()   { return Long.parseLong(scanner.nextLine().trim()); }
    private double readDouble() { return Double.parseDouble(scanner.nextLine().trim()); }
}