package com.driveeasy.service;

import com.driveeasy.exception.ResourceNotFoundException;
import com.driveeasy.exception.ValidationException;
import com.driveeasy.model.Car;
import com.driveeasy.model.enums.CarCategory;
import com.driveeasy.repository.CarRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;

@Service
@Transactional
public class CarService {

    private final CarRepository carRepository;

    public CarService(CarRepository carRepository) {
        this.carRepository = carRepository;
    }

    /**
     * Adds a new car. ID is auto-generated by the database.
     */
    public Car addCar(String model, CarCategory category,
                      double baseFare, double perKmRate, double perHourRate) {
        validatePricing(baseFare, perKmRate, perHourRate);
        Car car = new Car(model, category, baseFare, perKmRate, perHourRate);
        return carRepository.save(car);
    }

    /**
     * Updates all pricing fields atomically.
     */
    public Car updateCarPricing(Long carId,
                                double newBaseFare,
                                double newPerKmRate,
                                double newPerHourRate) {
        validatePricing(newBaseFare, newPerKmRate, newPerHourRate);
        Car car = findById(carId);
        car.setBaseFare(newBaseFare);
        car.setPerKmRate(newPerKmRate);
        car.setPerHourRate(newPerHourRate);
        return carRepository.save(car);
    }

    public Car markUnderMaintenance(Long carId) {
        Car car = findById(carId);
        if (car.isUnderMaintenance()) {
            throw new ValidationException("Car " + carId + " is already under maintenance");
        }
        car.setUnderMaintenance(true);
        return carRepository.save(car);
    }

    public Car markAvailable(Long carId) {
        Car car = findById(carId);
        if (!car.isUnderMaintenance()) {
            throw new ValidationException("Car " + carId + " is already available");
        }
        car.setUnderMaintenance(false);
        return carRepository.save(car);
    }

    @Transactional(readOnly = true)
    public Car findById(Long carId) {
        return carRepository.findById(carId)
                .orElseThrow(() -> new ResourceNotFoundException("Car not found with id: " + carId));
    }

    @Transactional(readOnly = true)
    public List<Car> getAllCars() {
        return carRepository.findAll();
    }

    @Transactional(readOnly = true)
    public List<Car> searchByCategory(CarCategory category) {
        return carRepository.findByCategory(category);
    }

    @Transactional(readOnly = true)
    public List<Car> searchByPriceRange(double minBaseFare, double maxBaseFare) {
        if (minBaseFare < 0 || maxBaseFare < minBaseFare) {
            throw new ValidationException("Invalid price range");
        }
        return carRepository.findByBaseFareBetween(minBaseFare, maxBaseFare);
    }

    @Transactional(readOnly = true)
    public List<Car> findAvailableCars(LocalDate startDate, LocalDate endDate) {
        return carRepository.findAvailableCars(startDate, endDate);
    }

    private void validatePricing(double baseFare, double perKmRate, double perHourRate) {
        if (baseFare < 0 || perKmRate < 0 || perHourRate < 0) {
            throw new ValidationException("Pricing values must not be negative");
        }
    }
}
